name: vargp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - seaborn
    - numpy
    - tqdm
    - fire
    - tensorboard
    - wandb
    - 'torch<1.5'
    - 'torchvision<0.6'
    - torch_optimizer
