## This is to check the Bayesian v/s MAP kernel hyperparameters.
method: grid
parameters:
  epochs:
    value: 1000
  M:
    value: 60
  lr:
    value: 0.002
  batch_size:
    value: 512
  beta:
    value: 10.0
  map_est_hypers:
    value: 1
  seed:
    values: [1, 2, 3, 4, 5]
command:
  - ${env}
  - python3
  - /mnt/share/sanyam/src/continual_gp/experiments/mnist.py
  - s-mnist
  - --data-dir=/mnt/share/sanyam/datasets
  - ${args}
