## This is to check the variational mean conditioning.
method: grid
parameters:
  n_tasks:
    value: 10
  epochs:
    value: 500
  M:
    values: [80, 100, 120, 140, 160, 180, 200, 220, 240, 260]
  lr:
    value: 0.002
  batch_size:
    value: 512
  beta:
    value: 3.0
  seed:
    value: 1
command:
  - ${env}
  - python3
  - /mnt/share/sanyam/src/continual_gp/experiments/mnist.py
  - p-mnist
  - --data-dir=/mnt/share/sanyam/datasets
  - ${args}
