## This is to check the variational mean conditioning.
method: random
parameters:
  n_tasks:
    value: 10
  epochs:
    value: 1000
  M:
    value: 100
  lr:
    value: 0.0037
  batch_size:
    value: 512
  beta:
    value: 1.64
command:
  - ${env}
  - python3
  - /mnt/share/sanyam/src/continual_gp/experiments/mnist.py
  - p-mnist
  - --data-dir=/mnt/share/sanyam/datasets
  - ${args}
