method: bayes
metric:
  name: task1/val/acc_best
  goal: maximize
parameters:
  n_tasks:
    value: 2
  epochs:
    value: 500
  M:
    min: 20
    max: 200
  lr:
    min: 0.001
    max: 0.01
  batch_size:
    value: 512
  beta:
    distribution: uniform
    min: 1.0
    max: 10.0
  ep_var_mean:
    value: 1
  seed:
    value: 10
command:
  - ${env}
  - python3
  - /mnt/share/sanyam/src/continual_gp/experiments/mnist.py
  - p-mnist
  - --data-dir=/mnt/share/sanyam/datasets
  - ${args}
