method: random
parameters:
  n_tasks:
    value: 5
  epochs:
    value: 1000
  M:
    values: [40, 60, 80, 100, 120, 140, 160, 180, 200]
  lr:
    value: 0.0037
  batch_size:
    value: 512
  beta:
    value: 1.64
  # ep_var_mean:
  #   values: [1, 0]
  # map_est_hypers:
  #   values: [0, 1]
command:
  - ${env}
  - python3
  - /mnt/share/sanyam/src/continual_gp/experiments/vargp.py
  - p-mnist
  - --data-dir=/mnt/share/sanyam/datasets
  - ${args}
