method: random
parameters:
  epochs:
    value: 500
  M:
    value: 60
  lr:
    value: 0.003
  batch_size:
    value: 512
  beta:
    value: 10.0
  # ep_var_mean:
  #   values: [1, 0]
  # map_est_hypers:
  #   values: [0, 1]
command:
  - ${env}
  - python3
  - /mnt/share/sanyam/src/continual_gp/experiments/vargp.py
  - s-mnist
  - --data-dir=/mnt/share/sanyam/datasets
  - ${args}
